### ISSUE TITLE
Data access

### ISSUE THREAD

**Issue by nickhsmith** [camyoung54/CopyClust#2]
Hello, I read your latest Bio Arxiv paper and wanted to thank you for creating a tool for IC classification. I was wondering if either your TCGA calls, or any scripts you can share with me to try to replicate your calls could be made available.

I know the vignette is a work in progress, but I downloaded the data files, and they seem to just be text labels and not actual TCGA/METABRIC data.

Please let me know if this can be made available before the review/publication process. Thanks

**Comment by camyoung54** [comment]
Certainly! I've uploaded all of the raw copy number data for the METABRIC, TCGA SNP, and TCGA WES datasets.
